### ISSUE TITLE
It is showing error on many files.

### ISSUE THREAD

**Issue by Abhinav1217** [basselin/php-minify#2]
I downloaded this and trying to test it. Here is my folder structure.

```
\--|
    |- Build/
    |- Main/
    |- demo.php 
    |- phpminify.php  
```

I have edited the demo to set source as `Main/` and target as `Build/`.

The source folder has 461 items but the Build folder only contains  218 items. 

For all the missing files,  The error message is same ( only difference is being filename.)

```
Warning: file_put_contents(./Build/Library/Monolog/Handler/FingersCrossed/ChannelLevelActivationStrategy.php): failed to open stream: No such file or directory in /var/www/Test/phpminify.php on line 187
PHP Warning:  file_put_contents(./Build/Library/Monolog/Handler/SyslogUdp/UdpSocket.php): failed to open stream: No such file or directory in /var/www/Test/phpminify.php on line 187

Warning: file_put_contents(./Build/Library/Monolog/Handler/SyslogUdp/UdpSocket.php): failed to open stream: No such file or directory in /var/www/Test/phpminify.php on line 187
```

```
PHP Warning:  file_put_contents(./Build/Library/Psr/Log/LoggerInterface.php): failed to open stream: No such file or directory in /var/www/Test/phpminify.php on line 187

Warning: file_put_contents(./Build/Library/Psr/Log/LoggerInterface.php): failed to open stream: No such file or directory in /var/www/Test/phpminify.php on line 187
PHP Warning:  file_put_contents(./Build/Library/Psr/Log/LogLevel.php): failed to open stream: No such file or directory in /var/www/Test/phpminify.php on line 187

Warning: file_put_contents(./Build/Library/Psr/Log/LogLevel.php): failed to open stream: No such file or directory in /var/www/Test/phpminify.php on line 187
PHP Warning:  file_put_contents(./Build/Library/Psr/Log/Test/LoggerInterfaceTest.php): failed to open stream: No such file or directory in /var/www/Test/phpminify.php on line 187

Warning: file_put_contents(./Build/Library/Psr/Log/Test/LoggerInterfaceTest.php): failed to open stream: No such file or directory in /var/www/Test/phpminify.php on line 187
PHP Warning:  file_put_contents(./Build/Library/Monolog/Processor/WebProcessor.php): failed to open stream: No such file or directory in /var/www/Test/phpminify.php on line 187
```

What could be wrong??

**Comment by Abhinav1217** [comment]
I tried to minify some other php application, and am facing same issue.

phpmyadmin  
Original - 1940 items.
target - 1284 items.

Bug tracker which I use,
Original - 829 Items,
Target -  675 Items.

Mini-CRM which I use,
Original 363 Items,
Target 218 Items.

All with same error on line 187.

**Comment by basselin** [comment]
Could you give me more information about your server and php version ?

**Comment by Abhinav1217** [comment]
I use Nginx server with php-fpm mainly but I have tested this in apache also. I use Fedora 22 and keep it updated. 
```
[Abhinav@abhinav-fed22 ~] $ nginx -v
nginx version: nginx/1.8.0
[Abhinav@abhinav-fed22 ~] $ httpd -v
Server version: Apache/2.4.16 (Fedora)
Server built:   Jul 17 2015 07:15:10
[Abhinav@abhinav-fed22 ~] $ php --version
PHP 5.6.11 (cli) (built: Jul 17 2015 07:31:17) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
[Abhinav@abhinav-fed22 ~] $ uname -a
Linux abhinav-fed22 4.1.3-200.fc22.x86_64 #1 SMP Wed Jul 22 19:51:58 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[Abhinav@abhinav-fed22 ~] $ 
```

**Comment by basselin** [comment]
I tried to compress phpMyAdmin (latest version) on various servers. I have had no problems.
Has the php script all the access read / write (folder, file) ? (see: `mkdir`)

**Comment by Abhinav1217** [comment]
Strange..  I just did `sudo chmod -R 777 Main/` and then run `php demo.php` again.  Result is same.  Original -> 1940 Items,  Target -> 1245 Items.  Excluding the 2 md files, still 693 files are missing.  

Have a look at this.
```
[Abhinav@abhinav-fed22 Test] $ tree Build/ > Target.txt
[Abhinav@abhinav-fed22 Test] $ tree Main/ > Source.txt
[Abhinav@abhinav-fed22 Test] $ tail Target.txt 
    ├── themes.php
    ├── transformation_overview.php
    ├── url.php
    ├── user_password.php
    ├── version_check.php
    ├── view_create.php
    ├── view_operations.php
    └── webapp.php

237 directories, 1006 files
[Abhinav@abhinav-fed22 Test] $ tail Source.txt 
    ├── transformation_overview.php
    ├── transformation_wrapper.php
    ├── url.php
    ├── user_password.php
    ├── version_check.php
    ├── view_create.php
    ├── view_operations.php
    └── webapp.php

237 directories, 1701 files
[Abhinav@abhinav-fed22 Test] $ ls
Build  demo.php  Main  phpminify.php  Source.txt  Target.txt
[Abhinav@abhinav-fed22 Test] $ 
```

**Comment by basselin** [comment]
Could you test the lastest `phpminify.php` ?
Exceptions are more explicit :)

**Comment by Abhinav1217** [comment]
Here is the output.  Still testing on phpmyadmin. 

Build folder has 0 items. 

```
[Abhinav@abhinav-fed22 Test] $ php demo.php 
PHP Fatal error:  Uncaught exception 'ErrorException' with message 'file_put_contents(./Build/phpMyAdmin/db_search.php): failed to open stream: No such file or directory' in /var/www/Test/phpminify.php:208
Stack trace:
#0 [internal function]: PhpMinify->addError(2, 'file_put_conten...', '/var/www/Test/p...', 208, Array)
#1 /var/www/Test/phpminify.php(208): file_put_contents('./Build/phpMyAd...', '<?php\n require_...')
#2 /var/www/Test/demo.php(14): PhpMinify->run()
#3 {main}

Next exception 'RuntimeException' with message 'file_put_contents('./Build/phpMyAdmin/db_search.php', '...') failed' in /var/www/Test/phpminify.php:211
Stack trace:
#0 /var/www/Test/demo.php(14): PhpMinify->run()
#1 {main}
  thrown in /var/www/Test/phpminify.php on line 211

Fatal error: Uncaught exception 'ErrorException' with message 'file_put_contents(./Build/phpMyAdmin/db_search.php): failed to open stream: No such file or directory' in /var/www/Test/phpminify.php:208
Stack trace:
#0 [internal function]: PhpMinify->addError(2, 'file_put_conten...', '/var/www/Test/p...', 208, Array)
#1 /var/www/Test/phpminify.php(208): file_put_contents('./Build/phpMyAd...', '<?php\n require_...')
#2 /var/www/Test/demo.php(14): PhpMinify->run()
#3 {main}

Next exception 'RuntimeException' with message 'file_put_contents('./Build/phpMyAdmin/db_search.php', '...') failed' in /var/www/Test/phpminify.php:211
Stack trace:
#0 /var/www/Test/demo.php(14): PhpMinify->run()
#1 {main}
  thrown in /var/www/Test/phpminify.php on line 211
[Abhinav@abhinav-fed22 Test] $ 
```

**Comment by basselin** [comment]
I have an idea !
Write the options with `realpath`:

``` php
$phpMinify = new PhpMinify(array(
    'source' => realpath('./phpMyAdmin-4.4.12-all-languages/'),
    'target' => realpath('.') . '/phpMyAdmin-4.4.12-all-languages.min/',
));
var_dump($phpMinify->run());
```

**Comment by Abhinav1217** [comment]
Same error as before. 
tried it with multiple combos of `dirname()` `realpath`, `__DIR__`  even the direct linux path. Tried  Both with and without trailing slash on the names.

**Comment by basselin** [comment]
Perhaps, the script is running too fast ?
Try using `usleep()` just after the line 222 ( before `} // for` )

http://php.net/manual/en/function.usleep.php

**Comment by Abhinav1217** [comment]
Added usleep(10000); both above and below bracket. 
Not working..
I added `touch($targetPathName)` just `above the file_put_contents`  which should create a blank file hoping to avoid error. But for some reason `Build/` is still empty. 

 I added some debug lines in `public function run()` at various points .

```
-------------
Source- /var/www/Test/Main/.
Target- /var/www/Test/Build/.
-------------
```

Above if just after you created `$sourcePathname` and `$targetPathname`.

```
-------------
Source- /var/www/Test/Main/phpMyAdmin/db_search.php
Target- /var/www/Test/Build/phpMyAdmin/db_search.php
-------------
```

Above one is the same. It ran 2nd time. 

```
-------------
Source- /var/www/Test/Main/phpMyAdmin/db_search.php
Target- /var/www/Test/Build/phpMyAdmin/db_search.php
object(SplFileInfo)#7 (2) {
  ["pathName":"SplFileInfo":private]=>
  string(43) "/var/www/Test/Main/phpMyAdmin/db_search.php"
  ["fileName":"SplFileInfo":private]=>
  string(13) "db_search.php"
}
-------------
```

Above one is right before file_put_contents. Here is the snippet. 

```
if ($value->isFile() && !in_array(strtolower($value->getExtension()), $this->getExclusions())) {
    if (in_array(strtolower($value->getExtension()), $this->getExtensions())) {
        $this->errorStart();
        echo '-------------'.PHP_EOL;
        echo 'Source- '.$sourcePathname.PHP_EOL;
        echo 'Target- '.$targetPathname.PHP_EOL;
        var_dump($value);
        echo '-------------'.PHP_EOL;
        echo PHP_EOL.PHP_EOL.PHP_EOL;

        $res = touch($targetPathname);
        $res = file_put_contents($targetPathname, $this->minify($sourcePathname));
```

**Comment by Abhinav1217** [comment]
I tried to directly use your minify function in my own function  

```
touch($target . DIRECTORY_SEPARATOR . $iterator->getSubPathName());
  file_put_contents($target . DIRECTORY_SEPARATOR . $iterator->getSubPathName(), $phpMinify->minify($item));
```

It showed errors for unidentified ASCII characters. Maybe I am calling it wrong.

Anyway, Due to short of time. I went old school   https://gist.github.com/Abhinav1217/7544b2b29124853604fb

Thanks for your time. These conversations was very educative.

**Comment by basselin** [comment]
Sorry not to have found a good solution :-/
